#klass info
Klass.create("Mutant", "Skill", "Tech", "Characters in the Mutant class possess the X-gene. At some point in their life, the gene surfaced, and a genetic mutation was born.")
Klass.create("Skill", "Science", "Mutant", "Characters in the Skill class are trained fighters. These characters don't rely on special powers to win fights.")
Klass.create("Science", "Mystic", "Skill", "Many characters in the Science class were genetically altered, often in freak accidents. However, some characters are instead unaltered but rely on science to fight.")
Klass.create("Mystic", "Cosmic", "Science", "Characters in the Mystic class are associated in some way with mysticism or magic.")
Klass.create("Cosmic", "Tech", "Mystic", "Characters in the Cosmic class are generally characters that come from space or other realms. However, some Cosmic characters were experimented on by species from outer space.")
Klass.create("Tech", "Mutant", "Cosmic", "Many characters in the Tech class are androids. However, some Tech characters are simply connected in some way to technology.")
Klass.create("Combined", "All", "None", "Combined Champions possess elements of at least two Classes.")

#Champion info Alternate version available
"Champion.create(Storm, December 10, 2014, Mutant)"
"Champion.create(Juggernaut, December 10, 2014, Mystic)"
"Champion.create(Hulk, December 10, 2014, Science)"
"Champion.create(Thor, December 10, 2014, Cosmic)"
"Champion.create(Rhino, December 10, 2014, Science)"
"Champion.create(Hawkeye, December 10, 2014, Skill)"
"Champion.create(Drax, December 10, 2014, Cosmic)"
"Champion.create(Abomination, December 10, 2014, Science)"
"Champion.create(Kang the Conqueror, December 10, 2014, Tech)"
"Champion.create(Superior Iron Man, February 19, 2015, Cosmic)"
"Champion.create(Rocket Raccoon, March 5, 2015, Tech)"
"Champion.create(Doctor Strange, March 19, 2015, Mystic)"
"Champion.create(Captain America (WWII), July 2, 2015, Science)"
"Champion.create(Black Widow, May 7, 2015, Skill)"
"Champion.create(Void, January 18, 2018, Science)"
"Champion.create(Sentry, January 4, 2018, Science)"
"Champion.create(Luke Cage, November 26, 2015, Science)"
"Champion.create(Groot, December 24, 2015, Cosmic)"
"Champion.create(Spider-Man (Miles Morales), January 7, 2016, Science)"
"Champion.create(Cyclops (Blue Team), January 21, 2016, Mutant)"
"Champion.create(Old Man Logan, February 4, 2016, Mutant)"
"Champion.create(Venompool, February 18, 2016, Cosmic)"
"Champion.create(She-Hulk, March 3, 2016, Science)"
"Champion.create(Wolverine (X-23), March 17, 2016, Mutant)"
"Champion.create(Ms. Marvel (Kamala Khan), March 31, 2016, Cosmic)"
"Champion.create(Agent Venom, April 14, 2016, Skill)"
"Champion.create(Red Hulk, April 28, 2016, Science)"
"Champion.create(Crossbones, May 12, 2016, Skill)"
"Champion.create(Black Panther (Civil War), May 26, 2016, Skill)"
"Champion.create(Falcon, June 9, 2016, Skill)"
"Champion.create(Civil Warrior, June 30, 2016, Tech)"
"Champion.create(Nightcrawler, July 7, 2016, Mutant)"
"Champion.create(Iron Fist (Immortal), August 20, 2015, Mystic)"
"Champion.create(Loki, August 4, 2016, Mystic)"
"Champion.create(Gambit, August 18, 2016, Mutant)"
"Champion.create(Karnak, September 1, 2016, Skill)"
"Champion.create(Rogue, September 15, 2016, Mutant)"
"Champion.create(Quake, September 29, 2016, Science)"
"Champion.create(Ultron (Classic), August 17, 2016, Tech)"
"Champion.create(Phoenix, October 13, 2016, Cosmic)"
"Champion.create(Ghost Rider, October 27, 2016, Mystic)"
"Champion.create(Mordo, November 10, 2016, Mystic)"
"Champion.create(Doctor Voodoo, November 24, 2016, Mystic)"
"Champion.create(Hyperion, December 8, 2016, Cosmic)"
"Champion.create(Howard the Duck, December 22, 2016, Tech)"
"Champion.create(Gwenpool, January 5, 2017, Skill)"
"Champion.create(Cable, January 19, 2017, Mutant)"
"Champion.create(The Hood, February 2, 2017, Mystic)"
"Champion.create(Iceman, March 30, 2017, Mutant)"
"Champion.create(Dormammu, February 16, 2017, Mystic)"
"Champion.create(Archangel, March 2, 2017, Mutant)"
"Champion.create(Spider-Man (Stark Enhanced), July 6, 2017, Tech)"
"Champion.create(Vulture, July 20, 2017, Tech)"
"Champion.create(Nebula, May 11, 2017, Tech)"
"Champion.create(Angela, April 13, 2017, Cosmic)"
"Champion.create(Carnage, June 8, 2017, Cosmic)"
"Champion.create(King Groot, April 27, 2017, Cosmic)"
"Champion.create(Medusa, September 14, 2017, Cosmic)"
"Champion.create(Morningstar, October 12, 2017, Mystic)"
"Champion.create(M.O.D.O.K., December 21, 2017, Science)"
"Champion.create(Mephisto, September 28, 2017, Mystic)"
"Champion.create(Psylocke, March 16, 2017, Mutant)"
"Champion.create(Kingpin, August 31, 2017, Skill)"
"Champion.create(Hela, November 23, 2017, Cosmic)"
"Champion.create(Thor (Ragnarok), November 9, 2017, Skill)"
"Champion.create(Hulk (Ragnarok), February 1, 2018, Science)"
"Champion.create(Sabretooth, March 29, 2018, Mutant)"
"Champion.create(Doctor Octopus, August 17, 2017, Tech)"
"Champion.create(Bishop, March 14, 2018, Mutant)"
"Champion.create(Taskmaster, December 7, 2017, Skill)"
"Champion.create(Yondu, May 25, 2017, Tech)"
"Champion.create(Captain America (Infinity War), May 10, 2018, Science)"
"Champion.create(Green Goblin, August 3, 2017, Tech)"
"Champion.create(Yellowjacket, July 30, 2015, Science)"
"Champion.create(Ant-Man, July 9, 2015, Science)"
"Champion.create(Domino, June 7, 2018, Mutant)"
"Champion.create(Deadpool, December 10, 2014, Mutant)"
"Champion.create(Colossus, December 10, 2014, Mutant)"
"Champion.create(Cyclops (New Xavier School), December 10, 2014, Mutant)"
"Champion.create(Wolverine, December 10, 2014, Mutant)"
"Champion.create(Magneto, June 18, 2015, Mutant)"
"Champion.create(Deadpool (X-Force), September 17, 2015, Mutant)"
"Champion.create(Goldpool, June 6, 2018, Mutant)"
"Champion.create(Magik, January 22, 2015, Mystic)"
"Champion.create(Blade, October 26, 2017, Skill)"
"Champion.create(Winter Soldier, December 10, 2014, Skill)"
"Champion.create(Black Panther, December 10, 2014, Skill)"
"Champion.create(Punisher, December 10, 2014, Skill)"
"Champion.create(Daredevil (Classic), April 16, 2015, Skill)"
"Champion.create(Moon Knight, September 24, 2015, Skill)"
"Champion.create(Elektra, October 8, 2015, Skill)"
"Champion.create(Wasp, July 5, 2018, Science)"
"Champion.create(Captain America, December 10, 2014, Science)"
"Champion.create(Electro, February 6, 2015, Science)"
"Champion.create(Joe Fixit, October 15, 2015, Science)"
"Champion.create(Spider-Gwen, November 12, 2015, Science)"
"Champion.create(Killmonger, February 15, 2018, Skill)"
"Champion.create(Black Bolt, December 10, 2014, Cosmic)"
"Champion.create(Gamora, December 10, 2014, Cosmic)"
"Champion.create(Ronan, December 10, 2014, Cosmic)"
"Champion.create(Thanos, August 17, 2016, Cosmic)"
"Champion.create(Ms. Marvel, April 2, 2015, Cosmic)"
"Champion.create(Spider-Man (Symbiote), September 10, 2015, Cosmic)"
"Champion.create(Iron Fist, December 10, 2014, Mystic)"
"Champion.create(Unstoppable Colossus, February 25, 2015, Mystic)"
"Champion.create(Guillotine, October 22, 2015, Mystic)"
"Champion.create(Thor (Jane Foster), December 10, 2015, Mystic)"
"Champion.create(Iron Man, December 10, 2014, Tech)"
"Champion.create(Vision, December 10, 2014, Tech)"
"Champion.create(Star-Lord, December 10, 2014, Tech)"
"Champion.create(Ultron, June 4, 2015, Tech)"
"Champion.create(Hulkbuster, May 21, 2015, Tech)"
"Champion.create(Iron Patriot, July 2, 2015, Tech)"
"Champion.create(Vision (Age of Ultron), May 14, 2015, Tech)"
"Champion.create(War Machine, August 13, 2015, Tech)"
"Champion.create(Ghost, July 19, 2018, Tech)"
"Champion.create(Sentinel, March 1, 2018, Tech)"
"Champion.create(Masacre, June 21, 2018, Skill)"
"Champion.create(Iron Man (Infinity War), May 24, 2018, Tech)"
"Champion.create(Corvus Glaive, April 26, 2018, Cosmic)"
"Champion.create(Proxima Midnight, April 12, 2018, Cosmic)"
"Champion.create(Wolverine (Weapon X), March 11, 2020, Mutant)"
"Champion.create(Heimdall, August 16, 2018, Cosmic)"
"Champion.create(Korg, August 30, 2018, Skill)"
"Champion.create(Red Skull, August 2, 2018, Tech)"
"Champion.create(Omega Red, September 13, 2018, Mutant)"
"Champion.create(Venom the Duck, October 16, 2018, Cosmic)"
"Champion.create(Symbiote Supreme, October 11, 2018, Mystic)"
"Champion.create(Ægon, November 22, 2018, Skill)"
"Champion.create(The Champion, November 8, 2018, Cosmic)"
"Champion.create(Darkhawk, December 20, 2018, Tech)"
"Champion.create(Night Thrasher, December 6, 2018, Skill)"
"Champion.create(Summoned Symbioid, October 2, 2018, Combined)"
"Champion.create(Thing, January 10, 2019, Science)"
"Champion.create(Diablo, January 24, 2019, Mystic)"
"Champion.create(Captain Marvel (Classic), January 8, 2015, Cosmic)"
"Champion.create(Captain Marvel, March 7, 2019, Cosmic)"
"Champion.create(Venom, October 29, 2015, Cosmic)"
"Champion.create(Ronin, May 2, 2019, Skill)"
"Champion.create(Cull Obsidian, May 16, 2019, Cosmic)"
"Champion.create(Ebony Maw, May 31, 2019, Mystic)"
"Champion.create(Human Torch, April 18, 2019, Science)"
"Champion.create(Annihilus, April 4, 2019, Cosmic)"
"Champion.create(Nick Fury, March 12, 2019, Skill)"
"Champion.create(Havok, February 7, 2019, Mutant)"
"Champion.create(Mister Sinister, February 11, 2019, Mutant)"
"Champion.create(Punisher 2099, June 29, 2017, Tech)"
"Champion.create(Invisible Woman, June 27, 2019, Science)"
"Champion.create(Namor, June 13, 2019, Mutant)"
"Champion.create(Mysterio, July 25, 2019, Tech)"
"Champion.create(Spider-Man (Stealth Suit), July 11, 2019, Skill)"
"Champion.create(Spider-Man (Classic), December 10, 2014, Science)"
"Champion.create(Sunspot, August 8, 2019, Mutant)"
"Champion.create(Warlock, August 22, 2019, Tech)"
"Champion.create(Vision (Aarkus), September 19, 2019, Cosmic)"
"Champion.create(Emma Frost, September 27, 2018, Mutant)"
"Champion.create(Beast, July 21, 2016, Mutant)"
"Champion.create(Black Widow (Claire Voyant), September 5, 2019, Mystic)"
"Champion.create(Doctor Doom, November 14, 2019, Mystic)"
"Champion.create(Elsa Bloodstone, October 3, 2019, Skill)"
"Champion.create(Man-Thing, October 17, 2019, Mystic)"
"Champion.create(Mister Fantastic, November 28, 2019, Science)"
"Champion.create(Guillotine 2099, October 31, 2019, Tech)"
"Champion.create(Silver Surfer, December 12, 2019, Cosmic)"
"Champion.create(Squirrel Girl, January 9, 2020, Skill)"
"Champion.create(Nova, January 23, 2020, Cosmic)"
"Champion.create(Longshot, February 13, 2020, Mystic)"
"Champion.create(Mojo, February 27, 2020, Mystic)"
"Champion.create(Mole Man, March 12, 2020, Skill)"
"Champion.create(Terrax, March 26, 2020, Cosmic)"
"Champion.create(Storm (Pyramid X), April 23, 2020, Mutant)"
"Champion.create(Sorcerer Supreme, April 9, 2020, Mystic)"
"Champion.create(Red Guardian, May 28, 2020, Science)"
"Champion.create(Black Widow (Deadly Origin), May 14, 2020, Skill)"
"Champion.create(Tigra, June 11, 2020, Mystic)"
"Champion.create(Hit-Monkey, June 25, 2020, Skill)"
"Champion.create(Guardian, July 9, 2020, Tech)"
"Champion.create(Sasquatch, July 23, 2020, Mystic)"
"Champion.create(Dragon Man, August 27, 2020, Mystic)"
"Champion.create(Platinumpool, September 2, 2020, Mutant)"
"Champion.create(Air-Walker, August 13, 2020, Cosmic)"
"Champion.create(Magneto (House of X), August 27, 2015, Mutant)"
"Champion.create(Professor X, September 10, 2020, Mutant)"
"Champion.create(Apocalypse, September 24, 2020, Mutant)"
"Champion.create(Cosmic Ghost Rider, October 22, 2020, Cosmic)"
"Champion.create(Red Goblin, October 8, 2020, Cosmic)"
"Champion.create(Hulk (Immortal), November 12, 2020, Science)"
"Champion.create(Abomination (Immortal), November 26, 2020, Science)"
"Champion.create(Daredevil (Hell's Kitchen), November 19, 2015, Skill)"
"Champion.create(Scarlet Witch (Classic), December 10, 2014, Mystic)"
"Champion.create(Spider-Ham, December 10, 2020, Science)"
"Champion.create(Jubilee, January 14, 2021, Mutant)"
"Champion.create(Stryfe, January 28, 2021, Mutant)"

#Alternate seed data
"Champion.create('Storm', 'December 10, 2014', 'Mutant')"
"Champion.create('Juggernaut', 'December 10, 2014', 'Mystic')"
"Champion.create('Hulk', 'December 10, 2014', 'Science')"
"Champion.create('Thor', 'December 10, 2014', 'Cosmic')"
"Champion.create('Rhino', 'December 10, 2014', 'Science')"
"Champion.create('Hawkeye', 'December 10, 2014', 'Skill')"
"Champion.create('Drax', 'December 10, 2014', 'Cosmic')"
"Champion.create('Abomination', 'December 10, 2014', 'Science')"
"Champion.create('Kang the Conqueror', 'December 10, 2014', 'Tech')"
"Champion.create('Superior Iron Man', 'February 19, 2015', 'Cosmic')"
"Champion.create('Rocket Raccoon', 'March 5, 2015', 'Tech')"
"Champion.create('Doctor Strange', 'March 19, 2015', 'Mystic')"
"Champion.create('Captain America (WWII)', 'July 2, 2015', 'Science')"
"Champion.create('Black Widow', 'May 7, 2015', 'Skill')"
"Champion.create('Void', 'January 18, 2018', 'Science')"
"Champion.create('Sentry', 'January 4, 2018', 'Science')"
"Champion.create('Luke Cage', 'November 26, 2015', 'Science')"
"Champion.create('Groot', 'December 24, 2015', 'Cosmic')"
"Champion.create('Spider-Man (Miles Morales)', 'January 7, 2016', 'Science')"
"Champion.create('Cyclops (Blue Team)', 'January 21, 2016', 'Mutant')"
"Champion.create('Old Man Logan', 'February 4, 2016', 'Mutant')"
"Champion.create('Venompool', 'February 18, 2016', 'Cosmic')"
"Champion.create('She-Hulk', 'March 3, 2016', 'Science')"
"Champion.create('Wolverine (X-23)', 'March 17, 2016', 'Mutant')"
"Champion.create('Ms. Marvel (Kamala Khan)', 'March 31, 2016', 'Cosmic')"
"Champion.create('Agent Venom', 'April 14, 2016', 'Skill')"
"Champion.create('Red Hulk', 'April 28, 2016', 'Science')"
"Champion.create('Crossbones', 'May 12, 2016', 'Skill')"
"Champion.create('Black Panther (Civil War)', 'May 26, 2016', 'Skill')"
"Champion.create('Falcon', 'June 9, 2016', 'Skill')"
"Champion.create('Civil Warrior', 'June 30, 2016', 'Tech')"
"Champion.create('Nightcrawler', 'July 7, 2016', 'Mutant')"
"Champion.create('Iron Fist (Immortal)', 'August 20, 2015', 'Mystic')"
"Champion.create('Loki', 'August 4, 2016', 'Mystic')"
"Champion.create('Gambit', 'August 18, 2016', 'Mutant')"
"Champion.create('Karnak', 'September 1, 2016', 'Skill')"
"Champion.create('Rogue', 'September 15, 2016', 'Mutant')"
"Champion.create('Quake', 'September 29, 2016', 'Science')"
"Champion.create('Ultron (Classic)', 'August 17, 2016', 'Tech')"
"Champion.create('Phoenix', 'October 13, 2016', 'Cosmic')"
"Champion.create('Ghost Rider', 'October 27, 2016', 'Mystic')"
"Champion.create('Mordo', 'November 10, 2016', 'Mystic')"
"Champion.create('Doctor Voodoo', 'November 24, 2016', 'Mystic')"
"Champion.create('Hyperion', 'December 8, 2016', 'Cosmic')"
"Champion.create('Howard the Duck', 'December 22, 2016', 'Tech')"
"Champion.create('Gwenpool', 'January 5, 2017', 'Skill')"
"Champion.create('Cable', 'January 19, 2017', 'Mutant')"
"Champion.create('The Hood', 'February 2, 2017', 'Mystic')"
"Champion.create('Iceman', 'March 30, 2017', 'Mutant')"
"Champion.create('Dormammu', 'February 16, 2017', 'Mystic')"
"Champion.create('Archangel', 'March 2, 2017', 'Mutant')"
"Champion.create('Spider-Man (Stark Enhanced)', 'July 6, 2017', 'Tech')"
"Champion.create('Vulture', 'July 20, 2017', 'Tech')"
"Champion.create('Nebula', 'May 11, 2017', 'Tech')"
"Champion.create('Angela', 'April 13, 2017', 'Cosmic')"
"Champion.create('Carnage', 'June 8, 2017', 'Cosmic')"
"Champion.create('King Groot', 'April 27, 2017', 'Cosmic')"
"Champion.create('Medusa', 'September 14, 2017', 'Cosmic')"
"Champion.create('Morningstar', 'October 12, 2017', 'Mystic')"
"Champion.create('M.O.D.O.K.', 'December 21, 2017', 'Science')"
"Champion.create('Mephisto', 'September 28, 2017', 'Mystic')"
"Champion.create('Psylocke', 'March 16, 2017', 'Mutant')"
"Champion.create('Kingpin', 'August 31, 2017', 'Skill')"
"Champion.create('Hela', 'November 23, 2017', 'Cosmic')"
"Champion.create('Thor (Ragnarok)', 'November 9, 2017', 'Skill')"
"Champion.create('Hulk (Ragnarok)', 'February 1, 2018', 'Science')"
"Champion.create('Sabretooth', 'March 29, 2018', 'Mutant')"
"Champion.create('Doctor Octopus', 'August 17, 2017', 'Tech')"
"Champion.create('Bishop', 'March 14, 2018', 'Mutant')"
"Champion.create('Taskmaster', 'December 7, 2017', 'Skill')"
"Champion.create('Yondu', 'May 25, 2017', 'Tech')"
"Champion.create('Captain America (Infinity War)', 'May 10, 2018', 'Science')"
"Champion.create('Green Goblin', 'August 3, 2017', 'Tech')"
"Champion.create('Yellowjacket', 'July 30, 2015', 'Science')"
"Champion.create('Ant-Man', 'July 9, 2015', 'Science')"
"Champion.create('Domino', 'June 7, 2018', 'Mutant')"
"Champion.create('Deadpool', 'December 10, 2014', 'Mutant')"
"Champion.create('Colossus', 'December 10, 2014', 'Mutant')"
"Champion.create('Cyclops (New Xavier School)', 'December 10, 2014', 'Mutant')"
"Champion.create('Wolverine', 'December 10, 2014', 'Mutant')"
"Champion.create('Magneto', 'June 18, 2015', 'Mutant')"
"Champion.create('Deadpool (X-Force)', 'September 17, 2015', 'Mutant')"
"Champion.create('Goldpool', 'June 6, 2018', 'Mutant')"
"Champion.create('Magik', 'January 22, 2015', 'Mystic')"
"Champion.create('Blade', 'October 26, 2017', 'Skill')"
"Champion.create('Winter Soldier', 'December 10, 2014', 'Skill')"
"Champion.create('Black Panther', 'December 10, 2014', 'Skill')"
"Champion.create('Punisher', 'December 10, 2014', 'Skill')"
"Champion.create('Daredevil (Classic)', 'April 16, 2015', 'Skill')"
"Champion.create('Moon Knight', 'September 24, 2015', 'Skill')"
"Champion.create('Elektra', 'October 8, 2015', 'Skill')"
"Champion.create('Wasp', 'July 5, 2018', 'Science')"
"Champion.create('Captain America', 'December 10, 2014', 'Science')"
"Champion.create('Electro', 'February 6, 2015', 'Science')"
"Champion.create('Joe Fixit', 'October 15, 2015', 'Science')"
"Champion.create('Spider-Gwen', 'November 12, 2015', 'Science')"
"Champion.create('Killmonger', 'February 15, 2018', 'Skill')"
"Champion.create('Black Bolt', 'December 10, 2014', 'Cosmic')"
"Champion.create('Gamora', 'December 10, 2014', 'Cosmic')"
"Champion.create('Ronan', 'December 10, 2014', 'Cosmic')"
"Champion.create('Thanos', 'August 17, 2016', 'Cosmic')"
"Champion.create('Ms. Marvel', 'April 2, 2015', 'Cosmic')"
"Champion.create('Spider-Man (Symbiote)', 'September 10, 2015', 'Cosmic')"
"Champion.create('Iron Fist', 'December 10, 2014', 'Mystic')"
"Champion.create('Unstoppable Colossus', 'February 25, 2015', 'Mystic')"
"Champion.create('Guillotine', 'October 22, 2015', 'Mystic')"
"Champion.create('Thor (Jane Foster)', 'December 10, 2015', 'Mystic')"
"Champion.create('Iron Man', 'December 10, 2014', 'Tech')"
"Champion.create('Vision', 'December 10, 2014', 'Tech')"
"Champion.create('Star-Lord', 'December 10, 2014', 'Tech')"
"Champion.create('Ultron', 'June 4, 2015', 'Tech')"
"Champion.create('Hulkbuster', 'May 21, 2015', 'Tech')"
"Champion.create('Iron Patriot', 'July 2, 2015', 'Tech')"
"Champion.create('Vision (Age of Ultron)', 'May 14, 2015', 'Tech')"
"Champion.create('War Machine', 'August 13, 2015', 'Tech')"
"Champion.create('Ghost', 'July 19, 2018', 'Tech')"
"Champion.create('Sentinel', 'March 1, 2018', 'Tech')"
"Champion.create('Masacre', 'June 21, 2018', 'Skill')"
"Champion.create('Iron Man (Infinity War)', 'May 24, 2018', 'Tech')"
"Champion.create('Corvus Glaive', 'April 26, 2018', 'Cosmic')"
"Champion.create('Proxima Midnight', 'April 12, 2018', 'Cosmic')"
"Champion.create('Wolverine (Weapon X)', 'March 11, 2020', 'Mutant')"
"Champion.create('Heimdall', 'August 16, 2018', 'Cosmic')"
"Champion.create('Korg', 'August 30, 2018', 'Skill')"
"Champion.create('Red Skull', 'August 2, 2018', 'Tech')"
"Champion.create('Omega Red', 'September 13, 2018', 'Mutant')"
"Champion.create('Venom the Duck', 'October 16, 2018', 'Cosmic')"
"Champion.create('Symbiote Supreme', 'October 11, 2018', 'Mystic')"
"Champion.create('Ægon', 'November 22, 2018', 'Skill')"
"Champion.create('The Champion', 'November 8, 2018', 'Cosmic')"
"Champion.create('Darkhawk', 'December 20, 2018', 'Tech')"
"Champion.create('Night Thrasher', 'December 6, 2018', 'Skill')"
"Champion.create('Summoned Symbioid', 'October 2, 2018', 'Combined')"
"Champion.create('Thing', 'January 10, 2019', 'Science')"
"Champion.create('Diablo', 'January 24, 2019', 'Mystic')"
"Champion.create('Captain Marvel (Classic)', 'January 8, 2015', 'Cosmic')"
"Champion.create('Captain Marvel', 'March 7, 2019', 'Cosmic')"
"Champion.create('Venom', 'October 29, 2015', 'Cosmic')"
"Champion.create('Ronin', 'May 2, 2019', 'Skill')"
"Champion.create('Cull Obsidian', 'May 16, 2019', 'Cosmic')"
"Champion.create('Ebony Maw', 'May 31, 2019', 'Mystic')"
"Champion.create('Human Torch', 'April 18, 2019', 'Science')"
"Champion.create('Annihilus', 'April 4, 2019', 'Cosmic')"
"Champion.create('Nick Fury', 'March 12, 2019', 'Skill')"
"Champion.create('Havok', 'February 7, 2019', 'Mutant')"
"Champion.create('Mister Sinister', 'February 11, 2019', 'Mutant')"
"Champion.create('Punisher 2099', 'June 29, 2017', 'Tech')"
"Champion.create('Invisible Woman', 'June 27, 2019', 'Science')"
"Champion.create('Namor', 'June 13, 2019', 'Mutant')"
"Champion.create('Mysterio', 'July 25, 2019', 'Tech')"
"Champion.create('Spider-Man (Stealth Suit)', 'July 11, 2019', 'Skill')"
"Champion.create('Spider-Man (Classic)', 'December 10, 2014', 'Science')"
"Champion.create('Sunspot', 'August 8, 2019', 'Mutant')"
"Champion.create('Warlock', 'August 22, 2019', 'Tech')"
"Champion.create('Vision (Aarkus)', 'September 19, 2019', 'Cosmic')"
"Champion.create('Emma Frost', 'September 27, 2018', 'Mutant')"
"Champion.create('Beast', 'July 21, 2016', 'Mutant')"
"Champion.create('Black Widow (Claire Voyant)', 'September 5, 2019', 'Mystic')"
"Champion.create('Doctor Doom', 'November 14, 2019', 'Mystic')"
"Champion.create('Elsa Bloodstone', 'October 3, 2019', 'Skill')"
"Champion.create('Man-Thing', 'October 17, 2019', 'Mystic')"
"Champion.create('Mister Fantastic', 'November 28, 2019', 'Science')"
"Champion.create('Guillotine 2099', 'October 31, 2019', 'Tech')"
"Champion.create('Silver Surfer', 'December 12, 2019', 'Cosmic')"
"Champion.create('Squirrel Girl', 'January 9, 2020', 'Skill')"
"Champion.create('Nova', 'January 23, 2020', 'Cosmic')"
"Champion.create('Longshot', 'February 13, 2020', 'Mystic')"
"Champion.create('Mojo', 'February 27, 2020', 'Mystic')"
"Champion.create('Mole Man', 'March 12, 2020', 'Skill')"
"Champion.create('Terrax', 'March 26, 2020', 'Cosmic')"
"Champion.create('Storm (Pyramid X)', 'April 23, 2020', 'Mutant')"
"Champion.create('Sorcerer Supreme', 'April 9, 2020', 'Mystic')"
"Champion.create('Red Guardian', 'May 28, 2020', 'Science')"
"Champion.create('Black Widow (Deadly Origin)', 'May 14, 2020', 'Skill')"
"Champion.create('Tigra', 'June 11, 2020', 'Mystic')"
"Champion.create('Hit-Monkey', 'June 25, 2020', 'Skill')"
"Champion.create('Guardian', 'July 9, 2020', 'Tech')"
"Champion.create('Sasquatch', 'July 23, 2020', 'Mystic')"
"Champion.create('Dragon Man', 'August 27, 2020', 'Mystic')"
"Champion.create('Platinumpool', 'September 2, 2020', 'Mutant')"
"Champion.create('Air-Walker', 'August 13, 2020', 'Cosmic')"
"Champion.create('Magneto (House of X)', 'August 27, 2015', 'Mutant')"
"Champion.create('Professor X', 'September 10, 2020', 'Mutant')"
"Champion.create('Apocalypse', 'September 24, 2020', 'Mutant')"
"Champion.create('Cosmic Ghost Rider', 'October 22, 2020', 'Cosmic')"
"Champion.create('Red Goblin', 'October 8, 2020', 'Cosmic')"
"Champion.create('Hulk (Immortal)', 'November 12, 2020', 'Science')"
"Champion.create('Abomination (Immortal)', 'November 26, 2020', 'Science')"
"Champion.create('Daredevil (Hell's Kitchen)', 'November 19, 2015', 'Skill')"
"Champion.create('Scarlet Witch (Classic)', 'December 10, 2014', 'Mystic')"
"Champion.create('Spider-Ham', 'December 10, 2020', 'Science')"
"Champion.create('Jubilee', 'January 14, 2021', 'Mutant')"
"Champion.create('Stryfe', 'January 28, 2021', 'Mutant')"